const mainPuzzles=[
{id:0,
    task:'Tanúhegyek',
    taskText:`A feladatod, hogy keresd meg a képet, amit valahol Európa belselyében, egy titkos helyen elrejtettem! Ha megtaláltad, kattints rá!`,
    imgSrc:'./img/pic/balatonFelvidek.jpg',
    imgBounds:[[46.81, 17.4487],[46.7957, 17.4766]],
    zoomLevelWhenVisible:11,
    tipp:'Ezek a hegyek egy réges-régi vulkán peremének megmaradt emlékei. Látod a képen, hogy mekkora hatalmas kráter volt itt hajdanán? Képzelj oda egy kört, ami összeköti az előtérben lévő két hegyet a távolival úgy, hogy a kör közepe valahol a hegyek közötti völgyben legyen. Szerencsére már 2,5 millió éve nem tört ki semmiféle tűzhányó ezen a vidéken, és a tudósok nem is számítanak újabb vulkánkitörésre. A hegyek környéke híres bortermő vidék, a közeli tópart pedig kedvelt nyaralóhely. Ez a tó egyébként Közép-Európa legnagyobb tava, a neve B-vel kezdödik, és N-re végzödik. Ez egy olyan támpont, amin érdemes elindulnod. Vajon melyik tó lehet ez? A képen látható hegyek a tó északi partján helyezkednek el. A távolabbi hegynek a nevéből is elárulok néhány betűt: _ A_A_S_N_ Most nem kapsz olyan videót, ami a keresett vidéket mutatja be. Úgy túl könnyű lenne a feladat. Viszont mutatok egy másikat, ami egy vulkánkitörést mutat. Ennek az az érdekessége, hogy az egész felülről látszik! Igen, felülről. A Nemzetközi Űrálommás épp akkor repült el a vulkán fölött, amikor az kitört, így az űrhajósok le tudták filmezni az eseményt.',
    videoSrc:'https://www.youtube.com/embed/Riauw5UTnW8',
    solved:false
},
{id:1,
    task:'Vörös tér',
    taskText:'A feladatod az lesz, hogy keresd meg a képet! Valahol a nagyvilágban, egy titkos helyen elrejtettem ezt a fényképet a térképen. Keresd meg, és ha megtaláltad, kattints rá! Ez egy olyan játék, ahol csalni szabad! Ha elakadsz, nyugodtan nézz utána bárhol, kerdezd meg valakitől, vagy akár keress rá a Google segítségével, ha nem menne fejből a megoldás!',
    imgSrc:'./img/pic/Moscow.jpg',
    imgBounds:[[55.753, 37.62],[55.756, 37.628]],
    zoomLevelWhenVisible:12,
    tipp:'Ez a fénykép abban a városban készült, amely a világ legnagyobb területű országának a fővárosa. Ez az ország olyan hatalmas, hogy két kontinensen terül el: Európában és Ázsiában. Az emberek itt cirill betűkkel írnak, és az ország nevét azzal az írásmóddal így kell leírni: Россия, a kiejtése pedig : Rosszíjá. Persze, magyarul másképp hivjuk ezt az országot, de nem árulhatom el, hogy mi az. Sejted már, hogy melyik városban rejtettem el a fényképet? A képen látható vörös színű várat KREML-nek hivják, az előtte található tér pedig a híres Vörös tér. Az előtérben látható jellegzetes, hagymakupolás templom neve Vaszilij Blazsennij-székesegyház. A tér középen álló kockaszerű épület pedig a Lenin-mauzóleum. Lenin régen az ország egyik híres vezetője volt. Amikor meghalt, testét bebalzsamozták, és ebben az épületben állították ki, hogy aki meg akarja őt nézni, az a mai napig is láthassa! A csatolt videó nagyon jól bemutatja a város téli hangulatát',
    videoSrc:'https://www.youtube.com/embed/rAxhaiNNfRk',
    solved:false
},
{id:2,
    task:'a császárváros',
    taskText:'ez a város nem Magyarországon van, mégis innen irányították a magyar királyok az országot. Melyik város lehet ez?',
    imgSrc:'./img/pic/wien.jpg',
    imgBounds:[[48.2051, 16.3613],[48.2017, 16.3693]],
    zoomLevelWhenVisible:14,
    tipp:'Ez a város egy szomszédos ország fővárosa, ahova leggyorsabban az M1-es autópályán lehet eljutni Budapestről. Amikor Magyarországon a Habsburg dinasztia uralkodott, ők még rengeteg másik országnak is az uralkodói voltak. A hatalmas birodalmukat innen, ebből a császárvárosból igazgatták. A város neve angolul Vienna, németül: W I _ _, magyarul pedig: _ _ C S. Többet nem segítek, mert ezt csak bemelegítő kérdésnek szánom!',
    videoSrc:'https://www.youtube.com/embed/cwenLWoeItQ',
    solved:false
},
{id:3,
    task:'ez őrület!',
    taskText:'Mindenképp látnod kell a videót! Egyszerűen megáll az ész! Van benne egy vagány krapek, aki olyan meredek lejtőkön száguldozik a biciklijével, ahol mások síelnek! Még a rendőröknek sem sikerül elcsípniük, olyan ügyesen csinálja!',
    imgSrc:'./img/pic/mountainBike.jpg',
    imgBounds:[[47.39, 12.617],[47.345, 12.66]],
    zoomLevelWhenVisible:9,
    tipp:'Ez lesz aztán az igazi nyomozós feladat! Ismét egy helyszínt kell megtalálnod, ezúttal azt, ahol ez a filmben látható őrült fickó száguldozott a biciklijével. Nézd végig a videót, és próbálj meg apró részletekből rájönni, hogy hol történt meg ez a kalandos eset! Ha sikeresen kitaláltad a helyszínt, csak meg kell keresned  a térképen, és ott már látni fogod a fényképet is, amire rá kell kattintanod. Annyit persze segítek, hogy ez a film egy síparadicsomban játszódik egy szomszédos országban, a tél kellős közepén, amikor ott éppen mindenki síel. A nyomozás során  az egyik támpont talán az lehet, hogy a síliftekre mindig ki van írva a nevük. Szerencsére több liftet is mutatnak a filmen egész közelről, és ha odafigyelsz, el is tudod olvasni a nevüket. Lehet, hogy ha ezekre rákeresel az interneten, úgy könnyen megtalálod magát a síparadicsomot is, ahonnan ezek indulnak, és így meglesz a titkos helyszín is! Van egy olyan jelenet is a filmben, amikor a fickó olyan gyorsan száguldozik a lejtőn, hogy a rendőrségi traffipax lefényképezi. Ha sikerül annál a pontnál megállítanod a videót, amikor egy pillanatra mutatják a fényképét, azon rajta van, hogy mennyivel száguldozott, no meg a kép aljára oda van írva a síparadicsom neve is. Ennyi segítség ugye elég lesz?',
    videoSrc:'https://www.youtube.com/embed/1CR0QmCaMTs',
    solved:false
},
{id:4,
    task:'Eiffel-torony',
    taskText:'Gyakoroljuk egy kicsit azt, hogy kitalálod, melyik város jelképe ez a torony!',
    imgSrc:'./img/pic/EiffelTower.jpg',
    imgBounds:[[48.8584, 2.2952],[48.8568, 2.2917]],
    zoomLevelWhenVisible:5,
    tipp:'Ez a torony a francia fővárosban található. A látványa a kezdetektől megosztotta Párizs polgárait. Ki rajong érte, ki gyűlöli, és panaszkodik, hogy micsoda ronda monstrum ez. Nézd meg a videót Párizsról, és döntsd el te magad, hogy kinek adsz igazat. Szerinted ez a torony hozzátesz-e ennek a hangulatos városnak a látványához, vagy inkább elcsúfítja a párizsi látképet? És mint mindig, most is keresd meg az Eiffel-torony fényképét magán a térképen is! Legyen az, hogy előbb megtalálod Franciaországot, aztán Párizst, onnan aztán már könnyű dolgod lesz!',
    videoSrc:'https://www.youtube.com/embed/72kRM86V-dw',
    solved:false
},
{id:5,
    task:'ez most akkor sziget vagy sem?',
    taskText:'Keresd meg ezt a hires bencés apátságot Franciaországban!',
    imgSrc:'./img/pic/Mont-Saint-Michel.jpg',
    imgBounds:[[48.6360, -1.5075],[48.6307, -1.4948]],
    zoomLevelWhenVisible:7,
    tipp:'Mont-Saint-Michel apátság Franciaországban, Normandia partjainál található. Hires arról, hogy dagálykor a tenger teljesen körbeveszi, apálykor pedig száraz lábbal át lehet oda sétálni. Az, hogy mi az apály, meg a dagály, egy későbbi feladatban alaposabban átnézzük majd. Most csak elég annyit megértened hozzá, hogy a tenger hol visszahúzódik (ez az apály), hol meg megárad (ilyenkor van dagály), és emiatt ez a középkori apátság néha teljesen elszigetelődik a szárazföldtől. Segítek abban, hogy merre találod meg az apátságot: ha Párizs irányából elindulsz az Atlanti-óceán fele, két félszigetet is látsz, ami belenyúlik a tengerbe. Ezek a félszigetek egy hatalmas tengeröblöt határolnak két oldalról. Ebben az öbölben olyan nevű szigetek találhatók, mint Guernsey és Jersey. Ha látsz ilyen szigeteket, akkor jó helyen keresel! Nézd végig alaposan ezt az öblöt, mert az egyik eldugott szegletében lapul a keresett apátság is! A videón is látszik, hogy nincs messzi a parttól akkor sem, amikor éppen ellepi a víz, úgyhogy ne az öböl mélyén, hanem valahol a tengerpart mentén keresgesd!',
    videoSrc:'https://www.youtube.com/embed/cvyx_p1Zl4U',
    solved:false
},
{id:6,
    task:'a mesterséges pálmafa alakú sziget és az ezernyi felhőkarcoló városa',
    taskText:'Van egy nagyon modern város a Perzsa (Arab-öböl partján, ahol a rengeteg gazdagságnak köszönhetően egy pillanat alatt nőnek ki a felhőkarcolók a sivatag homokjából. Nem is olyan rég csupán a kopár pusztaság volt ezen a helyen, most pedig egy modern világváros áll ugyanott!',
    imgSrc:'./img/pic/Dubai.jpg',
    imgBounds:[[25.2485, 55.1055],[25.20991, 55.185]],
    zoomLevelWhenVisible:10,
    tipp:'Dubai - ez a város egy rendkívül gazdag országban található, amit úgy hívnak, hogy Egyesült Arab Emírség (angolul a rövidítése UAE =United Arab Emirates). Rengeteg földgáz található az országban, ennek köszönhetően olyan nagy itt a gazdagság, hogy szinte barmit megengedhetnek maguknak, amit pénzzel meg lehet vásárolni. Éppen ezért olyan világvárost építtettek magunknak néhány évtized alatt a régi ütött-kopott Dubai helyén, aminek nehéz párját találni. Ezek az arabok úgy voltak vele, ha már egyszer csodavárost építenek, akkor csak a fantázia szabjon határt annak, hogy mi épülhet meg itt! Kitalálták például, hogy egy pálmafa alakú mesterséges szigetet építenek a tengerbe (ez a Pálma-sziget, és megsúgom, igazából mindjárt kettőt építettek), aztán felhúztak a világ legmagasabb épületét, egy 830 méter magas felhőkarcolót! Ez a híres Burj Khalifa. Valakinek síelni támad kedve a forró sivatagban? Semmi gond! Akkor építünk egy hűtött sícentrumot is, hogy igazi havon lehessen síelni! De van itt hét csillagos luxusszálloda is, ha valaki meg tudja fizetni a borsos szállásköltséget. Most még azt kell megbeszélnünk, merre találod Dubait. Szerintem a legegyszerűbb, ha veszel egy jegyet az Emirates légitársaság honlapján, és ok elvisznek oda! De a viccet félretéve: India és Afrika között van egy hatalmas félsziget. Ezt hívják Arab-félszigetnek. Több ország is osztozik a területén, például Szaúd-Arábia (ez mind közül a legnagyobb), Katar, Kuvait, az Egyesült Arab Emírségek, Jemen és Omán. Előszór is próbáld megkeresni ezt a hatalmas kiterjedésű félszigetet. Ha megtaláltad, utána keresd meg rajta az Emírségeket, és azon belül Dubai-t. Irány tehát Dubai, az ultramodern metropolisz!',
    videoSrc:'https://www.youtube.com/embed/wJV-mXehgdw',
    solved:false
},
{id:7,
    task:'香港, a nyüzsgő kínai metropolisz',
    taskText:'Remélem, tudsz kínai írásjeleket olvasni? Mert anélkül nehéz lesz kitalálnod, hogy hova rejtettem el ezt a képet, ami egyébként a Viktória-öbölről készült! Ha nem tudsz kínaiul, akkor se add fel, inkább válaszold meg a lenti kérdést, és a hátoldalon elárulom neked a város nevét!',
    imgSrc:'./img/pic/Hong_Kong.jpg',
    imgBounds:[[22.30, 114.195],[22.308, 114.22]],
    zoomLevelWhenVisible:10,
    tipp:'Hong Kong, ez a nyüzsgő, sosem alvó metropolisz Ázsiában található, a hatalmas területű és lakosságú Kína déli részén, a Dél-kínai-tenger partján. Keresd meg Ázsiában Kínát, Taiwant, Fülöp-szigeteket, Bruneit, Indonéziát, és Vietnámot. Ezek az országok veszik körbe a Dél-kínai-tengert, aminek a partján ez a nagyváros található. Nekem egyébként Hong Kong a kedvenc városom. Hogy miért? Nézd meg ezt a videót, hogy egy kis ízelítőt kapj a város hangulatából!',
    videoSrc:'https://www.youtube.com/embed/gYO1uk7vIcc',
    solved:false
},
{id:8,
    task:'ez a világ teteje',
    taskText:'A feladatod az, hogy megkeresd a világ tetejét, ezt a 8848 méter magas hegycsúcsot!',
    imgSrc:'./img/pic/Mount_Everest.jpg',
    imgBounds:[[28.028, 86.875],[27.99, 86.965]],
    zoomLevelWhenVisible:8,
    tipp:'A világ legmagasabb hegye Ázsiában, Nepál és Kína határvidékékén található. Itt a Himalája, ez a hatalmas hegylánc emelkedik az ég felé, amiben több olyan hegycsúcs is van, aminek a magassága meghaladja a 8000 métert! De mind közül a Mount Everest a legmagasabb, amit a helyiek Csomolungmának is neveznek. Ezt a hegyet látod a fényképen is. Ez már olyan magas, hogy a csúcs közelében alig van oxigén, ezért a hegymászóknak rendkívül nehéz ide feljutniuk. A videó is egy expedíció csúcstámadását mutat be, ahogy a hegymászók küszködve, zihálva végül felérnek ide, a világ tetejére. Segítek, hogy miképp keresd meg ezt a hegyet a térképen. Előbb keresd meg  Ázsiát, azon belül  pedig két országot:  Kínát, és Nepált. Majd ezután Nepálban keresd a fővárost, Katmandu-t. Ha ezzel megvagy, utána pedig próbáld meg fellelni Kína Nepállal határos tartományát, Tibetet, és annak a székhelyét, Lhasa-t. Erre azért van szükség, mert ha összekötöd a képzeletben ezt a két várost (Katmandut és Lhasa-t) , körülbelül ott, ahol ez a vonal metszi a Kína és Nepál közti határt, ott van a világ legmagasabb hegye is, és ott találod az elrejtett fényképet is!',
    videoSrc:'https://www.youtube.com/embed/NhBzhi9jPFs',
    solved:false
},
{id:9,
    task:'a Titanic roncsai',
    taskText:'A feladatod most az lesz, hogy találj meg egy elsüllyedt hajót az óceán mélyén! Nem kell pánikolni a feladattól, végtére is a bolygó felszínének csupán 2/3-ad részét borítja víz. Mi az neked átnézni ezt a végtelen vízfelületet, nem igaz?',
    imgSrc:'./img/pic/Titanic.jpg',
    imgBounds:[[41.2, -49.35],[40.995, -48.9386]],
    zoomLevelWhenVisible:7,
    tipp:'Hallottál már az elsüllyedt Titanicról? Ez egy szerencsétlenül járt hajó neve, amiről a kortársai azt tartották -mint aztán kiderült, alaptalanul-, hogy elsüllyeszthetetlen. Az volt a legelső és egyben az utolsó útja, amikor elindult az angliai Southampton kikötőjéből New Yorkba, és megtörtént vele a szörnyű tragédia. Sajnos a nyílt óceánon nekiütközött egy hatalmas jéghegynek. A baleset olyan hatalmas lyukat ütött a hajó oldalán, hogy akármit is tartottak róla, az mégiscsak elsüllyedt, és 1500 embert vitt magával a hullámsírba. A hajó roncsai azóta is a tengerfenéken pihennek. A kutatóknak sikerült megtalálni a helyszínt, ahol mindez történt: Az Atlanti-óceánban, kb. 600 kilométerre dél-dél-keleti irányban Újfundland partjaitól. A Titanic roncsainak koordinátai a következők: 41°, -49°. Ha még nem találkoztál ilyen jelöléssel, ez az úgynevezett koordináta rendszer. A térképészek ezt használják arra, hogy földrajzi helyeket pontosan beazonosítsanak. Láttál már olyan térképet, amire négyzetrács-szerű vonalak voltak rárajzolva? Na, az például ugyanez a koordináta rendszer. Úgy működik, hogy képzeletbeli vízszintes és függőleges vonalakkal hálózzak be az egész térképet. Ezeket a vonalakat számokkal jelölik. A koordináta első száma jelöli a vízszintes vonalnak a számát, a második pedig a függőlegesét. Ahhoz, hogy megtaláld a hajó roncsait, ennél többet most nem is kell értened a koordináta rendszerhez, ugyanis kapsz tőlem további segítséget. Talán már észrevetted, ahogy mozgatod a térkép fölött az egeret, az egér mutató mellett két kis szám látható. Mi ez a két szám? Hát annak a földrajzi pontnak a koordinátai, ami fölött a mutató éppen tartózkodik. Figyeld meg azt, hogy ha függőlegesen mozgatod az egeret, akkor csak az első szám változik a mutató mellett. Ha pedig balról jobbra, jobbról balra mozgatod, akkor meg a második szám. Ha meg összevissza, akkor mindkettő, ahogy újabb és újabb koordináta pontok felé viszed az egeredet. Hogy megtaláld a roncsokat a végtelen nagy Atlanti-óceánban, próbáld meg azt, hogy lekicsinyíted a térképed x3, x4 vagy x5-szörös nagyításra. Aztán megkeresed rajta Angliát és az Egyesült Államokat. Miért éppen ezt a két országot? Mert azt tudjuk, hogy a hajó az egyik országból elindult, a másikba pedig el akart jutni, tehát valahol e kettő közötti területen vezetett át a végzetes útja. Kérlek, mindjárt állítsd is be a térképen középre ezt a területet, ami egyébként még így is hatalmas régió, de legalább már tudjuk, hogy körülbelül hol kell keresnünk a hajóroncsot. Sok más támpont nincs, mert a baleset a nyílt vízen történt, semmi sziget vagy szárazföld nem volt a közelben, éppen ezert lesz szükségünk arra, hogy a koordináta rendszert is használjuk.  Ha beállítottad középre, amit látsz magad előtt az az Atlanti-óceán északi medencéje. Ez a hatalmas víztömeg választja el Európát és Észak-Amerikát egymástól, és ebben kell tovább keresnünk a hajó roncsait. Ha ezzel idáig megvagy, akkor kezd el az egeredet óvatosan mozgatni függőlegesen, és figyeld meg, hogy az egér mutató mellett az első szám hogyan változik. Ha felfele mozgatod, a szám növekszik, ha lefele, akkor pedig csökken. Most tedd meg azt, hogy addig mozgatod, amíg meg nem találod a 41-es számot. Ha ez megvan, akkor próbáld meg vízszintesen mozgatni az egeret. Most mar ne mozogjon fel-le, csak balról jobbra vagy jobbról balra. Ha ügyesen csinálod, akkor most a második számnak kell folyamatosan változnia. Az egeret addig mozgasd, amíg nem látod második számként a mínusz 49-et, de ügyelve arra, hogy lehetőleg az első szám se változzon meg közben. Ha pontosan beállítottál mindent, és az egér mutató mellett azt látod, hogy 41°, -49°, akkor megtaláltad a helyszínt már csak bele kell nagyítanod a térképbe, és előbukkan a keresett hajóroncs! A videó egy számítógépes szimuláción mutatja be, hogy süllyedt el a Titanic.',
     videoSrc:'https://www.youtube.com/embed/FSGeskFzE0s',
    solved:false
},
{id:10,
    task:'miért mozog a palackban a víz?',
    taskText:'mert a Hold magához vonnza! Ez lesz az árapályos feladat, amiről korábban beszéltem',
    imgSrc:'./img/pic/bayoffundy.jpg',
    imgBounds:[[45.2906, -65.983],[45.0111, -65.397]],
    zoomLevelWhenVisible:6,
    tipp:'Az árapály (apály és dagály váltakozása) egy nagyon érdekes jelenség, amit a tengerpartokon lehet megfigyelni. A Holdnak -ami egyébként nagyon-nagyon messze van tőlünk-, mégis érződik a gravitációs hatása idelenn a Földön. Még biztos nem tanultál a gravitációról, ezert gyorsan elmagyarázom dióhéjban, mi is ez: ez egy természeti jelenség. Másképp meg tömegvonzásnak is hívjak. A nevében is benne van, hogy a tömeg, azaz egy nagy mennyiségben felhalmozódott anyag vonz magához minden más anyagot. Kicsit olyan, mint a mágnes, csak ez mindenre hat, nem csupán a fémekre. Ez a gravitációs vonzás nagyon-nagyon-nagyon csekély. Emiatt rengeteg anyagnak kell felhalmozódnia együtt, hogy a hatást egyáltalán egy picit is észlelni lehessen. A két kulcsszó itt az, hogy ez a vonzás nagyon-nagyon kicsi, másrészt hogy nagyon-nagyon-nagyon sok anyagnak kell egyszerre együtt lenni ahhoz, hogy ez az egész működjön. De láss csodát, vannak ám a világon olyan testek, például egy bolygó pont ilyen, amelyben olyan hatalmas mennyiségű anyag van felhalmozódva, hogy az a roppant méreténél fogva bizony ki tud fejteni akkora gravitációs hatást, aminek a vonzását már észlelni lehet. A Föld, ahol mi is élünk, vagy a Hold odafenn az égen is már ilyen méretű égitest. Így a Hold tömegvonzását tőle nagyon-nagyon messzire, idelenn a Földön is észlelni lehet. Persze nem túl erősen, tehát nem kell attól félned, hogy felszippant az égbe, vagy ilyesmi, de a Föld felszínén található víztömeget bizony meg tudja mozdítani! És ez az árapály jelenség, ahogy a víz egy kicsit elkezd áramlani abba az irányba, amerre éppen a Hold jár az égbolton! Mivel a Hold hol itt-hol meg amott jár az égen, a tengerpartok mentén is a víz hol visszahúzódik, hol meg jobban megindul a partok fele. Az apály és dagály váltakozása napjában kétszer fordul elő, és a tengerpart domborzatától függ, hogy mennyire látványos. Valahol alig feltűnő, máshol meg nagyon is szembetűnő, hogy mekkora utat képes megtenni ilyenkor a víz! Ez a jelenség egyébként nem csak a tengerek vizére érvényes. A palackozott vízre, vagy a Duna folyására is pontosan ugyanúgy hat ám a Hold vonzása! Csak ezeknél olyan elhanyagolható a változás, hogy az egész jelenség teljességgel észrevehetetlen. Azt képzeld el, hogy egy óceán átlagosan 4 kilométer mély. Most jön a matek, figyelj! Mennyi is ez a négy kilométer méterre átszámolva? Várjunk csak… a kiló ugyebár ezret jelent, akkor az négyszer ezer, azaz 4000 méter! Szóval ez a 4000 méter magas vízoszlop méretéhez képest okoz az árapály jelenség mindössze 1-2 méteres mozgást. Ez szinte semmi! Viszont találtam neked egy olyan helyet a világon, ahol egy szerencsés földrajzi adottságnak köszönhetően ez az árapály jelenség egész extrém méreteket ölt. Néha a legalacsonyabb vízállás és a legmagasabb között akár 14 méteres különbség is lehet, és emiatt ez hely igazi világrekorder! Tudod, mit? Keressük is meg ezt a helyet a térképen, rendben? Ez egy tengeröböl, amit keresünk, és Észak-Amerikában van. Előbb keresd meg a kontinenst, aztán ha megvan, keresd meg benne Kanadát. Könnyű dolgod lesz, mert Észak-Amerikában nincs túl sok ország, és Kanada amúgy is olyan hatalmas méretű, hogy könnyű megtalálni a térképen. Kanadát két óceán is határolja, egyik a keleti, másik a nyugati partján. Keresd meg ezek közül,azt, ami a keleti partján van, azaz az Atlanti-óceánt. Ez az, amelyik elválasztja Európát Amerikától. Ebben az óceánban keresgettük már korábban a Titanic roncsait, ha még emlékszel a korábbi feladatra. Kanada tartományokra van felosztva. Az Atlanti-óceán partvidékén keresd meg azt a két kanadai tartományt, amit úgy hívnak, hogy New Brunswick és Nova Scotia . Ez a két tartomány zárja közre a Fundy-öblöt, amit mi keresünk. Ez az a világrekorder hely, ahol a világ legmagasabb dagályát lehet észlelni. Egy-egy ilyen alkalommal, amikor ez bekövetkezik, az óceán felől több víz áramlik be ebbe az egyetlen öbölbe, mint amennyi víz van a világ összes folyójában együttvéve! Lentebb megnézheted a videón is, milyen gyorsított felvételen, milyen a világ legnagyobb árapálya itt, a Fundy-öbölben!',
    videoSrc:'https://www.youtube.com/embed/TtWsL2hKfsY',
    solved:false
},
{id:11,
    task:'most legyen egy helyszín a Föld déli féltekéről is!',
    taskText:'ugorjunk hát el egy olyan kontintensre, ahol simán eléd ugorhat egy kenguru!',
    imgSrc:'./img/pic/australia_kangaroo.jpg',
    imgBounds:[[-23.6535,133.7640],[-23.8508,133.9803]],
    zoomLevelWhenVisible:9,
    tipp:'A kontinens kellős közepén van egy Alice Springs nevű városka, oda rakták ki ezt a táblát. Többet nem is segítek, mert ez alapján a kontinenst is könnyű megtalálni, meg a kellős közepén a varost is. Jó nyomozást!',
    videoSrc:'https://www.youtube.com/embed/Al5DMTjeQwM',
    solved:false
},
];

const helperQuestions=[
{id:0,
    question:'Melyik kontinensen található az Amazonas-folyó?',
    questionType:'folyó',
    answ1:'Dél-Amerika',
    answ2:'Ázsia',   
    answ3:'Észak-Amerika',
    answCorr:'Dél-Amerika'
},
{id:1,
    question:'Melyik kontinensen található a Mississippi-folyó?',
    questionType:'folyó',
    answ1:'Dél-Amerika',
    answ2:'Észak-Amerika',   
    answ3:'Ázsia',
    answCorr:'Észak-Amerika'
},
{id:2,
    question:'Melyik kontinensen található a Mekong-folyó?',
    questionType:'folyó',
    answ1:'Afrika',
    answ2:'Észak-Amerika',   
    answ3:'Ázsia',
    answCorr:'Ázsia'
},
{id:3,
    question:'Melyik kontinensen található a Nílus-folyó?',
    questionType:'folyó',
    answ1:'Afrika',
    answ2:'Ausztrália',   
    answ3:'Ázsia',
    answCorr:'Afrika'
},
{id:4,
    question:'Melyik kontinensen található a Volga-folyó?',
    questionType:'folyó',
    answ1:'Afrika',
    answ2:'Európa',   
    answ3:'Ázsia',
    answCorr:'Európa'
},
{id:5,
    question:'Melyik országon folyik keresztül a Jangce-folyó?',
    questionType:'folyó',
    answ1:'Egyiptom',
    answ2:'India',   
    answ3:'Kína',
    answCorr:'Kína'
},
{id:6,
    question:'Melyik országon folyik keresztül a Jenyiszej-folyó?',
    questionType:'folyó',
    answ1:'Oroszország',
    answ2:'Brazília',   
    answ3:'Kína',
    answCorr:'Oroszország'
},
{id:7,
    question:'Melyik országon folyik keresztül a Sárga-folyó?',
    questionType:'folyó',
    answ1:'Kanada',
    answ2:'Kína',   
    answ3:'Németország',
    answCorr:'Kína'
},
{id:8,
    question:'Melyik ország fővárosa Madrid?',
    questionType:'város',
    answ1:'Olaszország',
    answ2:'Portugália',   
    answ3:'Spanyolország',
    answCorr:'Spanyolország'
},
{id:9,
    question:'Melyik ország fővárosa New York?',
    questionType:'város',
    answ1:'egyiké sem',
    answ2:'Amerikai Egyesült Államok',   
    answ3:'Kanada',
    answCorr:'egyiké sem'
},
{id:10,
    question:'Melyik ország fővárosa Dublin?',
    questionType:'város',
    answ1:'Skócia',
    answ2:'Írország',   
    answ3:'Izland',
    answCorr:'Írország'
},
{id:11,
    question:'Melyik ország fővárosa Stockholm?',
    questionType:'város',
    answ1:'Finnország',
    answ2:'Dánia',   
    answ3:'Svédország',
    answCorr:'Svédország'
},
{id:12,
    question:'Melyik ország fővárosa Helsinki?',
    questionType:'város',
    answ1:'Finnország',
    answ2:'Dánia',   
    answ3:'Svédország',
    answCorr:'Finnország'
},
{id:13,
    question:'Melyik ország fővárosa Párizs?',
    questionType:'város',
    answ1:'Németország',
    answ2:'Franciaország',   
    answ3:'Belgium',
    answCorr:'Franciaország'
},
{id:14,
    question:'Melyik ország fővárosa Varsó?',
    questionType:'város',
    answ1:'Litvánia',
    answ2:'Oroszország',   
    answ3:'Lengyelország',
    answCorr:'Lengyelország'
},
{id:15,
    question:'Melyik ország fővárosa Tokió?',
    questionType:'város',
    answ1:'Japán',
    answ2:'Kína',   
    answ3:'Vietnám',
    answCorr:'Japán'
},
{id:16,
    question:'Melyik ország fővárosa Hanoi?',
    questionType:'város',
    answ1:'Japán',
    answ2:'Vietnám',   
    answ3:'Laosz',
    answCorr:'Vietnám'
},
{id:17,
    question:'Melyik ország fővárosa Kairó?',
    questionType:'város',
    answ1:'Algéria',
    answ2:'Marokkó',   
    answ3:'Egyiptom',
    answCorr:'Egyiptom'
},
{id:18,
    question:'Melyik ország fővárosa Nairobi?',
    questionType:'város',
    answ1:'Kenya',
    answ2:'Tanzánia',   
    answ3:'Mozambik',
    answCorr:'Kenya'
},
{id:19,
    question:'Melyik ország fővárosa Buenos Aires?',
    questionType:'város',
    answ1:'Uruguay',
    answ2:'Argentína',   
    answ3:'Chile',
    answCorr:'Argentína'
},
{id:20,
    question:'Melyik ország fővárosa Washington?',
    questionType:'város',
    answ1:'Mexikó',
    answ2:'Kanada',   
    answ3:'Amerikai Egyesült Államok',
    answCorr:'Amerikai Egyesült Államok'
},
{id:21,
    question:'Mi Csehország fővárosa?',
    questionType:'város',
    answ1:'Prága',
    answ2:'Pozsony',   
    answ3:'Ljubljana',
    answCorr:'Prága'
},
{id:22,
    question:'Mi Törökország fővárosa?',
    questionType:'város',
    answ1:'Izmir',
    answ2:'Ankara',   
    answ3:'Isztanbul',
    answCorr:'Ankara'
},
{id:23,
    question:'Mi Görögország fővárosa?',
    questionType:'város',
    answ1:'Thesszaloniki',
    answ2:'Larnaka',   
    answ3:'Athén',
    answCorr:'Athén'
},
{id:24,
    question:'Mi Portugália fővárosa?',
    questionType:'város',
    answ1:'Lisszabon',
    answ2:'Porto',   
    answ3:'Madrid',
    answCorr:'Lisszabon'
},
{id:25,
    question:'Mi Belgium fővárosa?',
    questionType:'város',
    answ1:'nincs fővárosa',
    answ2:'Brüsszel',   
    answ3:'Amszterdam',
    answCorr:'Brüsszel'
},
{id:26,
    question:'Mi az Egyesült Királyság fővárosa?',
    questionType:'város',
    answ1:'Anglia',
    answ2:'Dublin',   
    answ3:'London',
    answCorr:'London'
},
{id:27,
    question:'Mi Ukrajna fővárosa?',
    questionType:'város',
    answ1:'Kiev',
    answ2:'Kursk',   
    answ3:'Lvov',
    answCorr:'Kiev'
},
{id:28,
    question:'Mi Fehéroroszország fővárosa?',
    questionType:'város',
    answ1:'nincs is ilyen ország',
    answ2:'Minszk',   
    answ3:'Moszkva',
    answCorr:'Minszk'
},
{id:29,
    question:'Mi Kolumbia fővárosa?',
    questionType:'város',
    answ1:'Medellin',
    answ2:'Cali',   
    answ3:'Bogota',
    answCorr:'Bogota'
},
{id:30,
    question:'Mi Irán fővárosa?',
    questionType:'város',
    answ1:'Teherán',
    answ2:'Isfahan',   
    answ3:'Kabul',
    answCorr:'Teherán'
},
{id:31,
    question:'Mi Mexikó fővárosa?',
    questionType:'város',
    answ1:'California',
    answ2:'Mexikóváros',   
    answ3:'San Jose',
    answCorr:'Mexikóváros'
},
];


//http://www.webweaver.nu/html-tips/favicon.shtml
export { mainPuzzles, helperQuestions };